theme: jekyll-theme-Cayman
title: Shreya Upadhyay
logo: /assets/img/Shreya_IEEE.png
#show_downloads: true
#description: Bookmark this to keep an eye on my project updates!
#![EEG Band Discovery](/assets/img/eeg_band_discovery.jpeg)
